// Aura Data with rarities
const AURAS = [
    { name: "Nothing", rarity: 1, tier: "common" },
    { name: "Common", rarity: 2, tier: "common" },
    { name: "Basic", rarity: 2, tier: "common" },
    { name: "Simple", rarity: 2, tier: "common" },
    { name: "Plain", rarity: 2, tier: "common" },
    { name: "Ordinary", rarity: 2, tier: "common" },
    { name: "Standard", rarity: 2, tier: "common" },
    { name: "Uncommon", rarity: 4, tier: "uncommon" },
    { name: "Good", rarity: 5, tier: "uncommon" },
    { name: "Natural", rarity: 8, tier: "uncommon" },
    { name: "Rare", rarity: 16, tier: "rare" },
    { name: "Divinus", rarity: 32, tier: "rare" },
    { name: "Star", rarity: 50, tier: "rare" },
    { name: "Crystallized", rarity: 64, tier: "rare" },
    { name: "★", rarity: 100, tier: "rare" },
    { name: "Rage", rarity: 128, tier: "rare" },
    { name: "Topaz", rarity: 150, tier: "rare" },
    { name: "Glacier", rarity: 256, tier: "epic" },
    { name: "Ruby", rarity: 350, tier: "epic" },
    { name: "Forbidden", rarity: 1200, tier: "epic" },
    { name: "Forbidden: ERROR", rarity: 850000000, tier: "transcendent" },
    { name: "Emerald", rarity: 1350, tier: "epic" },
    { name: "Gilded", rarity: 512, tier: "epic" },
    { name: "Espresso", rarity: 550, tier: "epic" },
    { name: "Espresso: Double Shot", rarity: 3300, tier: "legendary" },
    { name: "Latte", rarity: 600, tier: "epic" },
    { name: "Latte: Caramel", rarity: 3600, tier: "legendary" },
    { name: "Ink", rarity: 700, tier: "epic" },
    { name: "Cappuccino", rarity: 720, tier: "epic" },
    { name: "Cappuccino: Foam Art", rarity: 4320, tier: "legendary" },
    { name: "Jackpot", rarity: 777, tier: "epic" },
    { name: "Sapphire", rarity: 800, tier: "epic" },
    { name: "Mocha", rarity: 850, tier: "epic" },
    { name: "Mocha: Dark Chocolate", rarity: 5100, tier: "legendary" },
    { name: "Aquamarine", rarity: 900, tier: "epic" },
    { name: "Wind", rarity: 900, tier: "epic" },
    { name: "Vanilla", rarity: 920, tier: "epic" },
    { name: "Vanilla: Bean", rarity: 5520, tier: "legendary" },
    { name: "★★", rarity: 1000, tier: "legendary" },
    { name: "Cinnamon", rarity: 1100, tier: "legendary" },
    { name: "Cinnamon: Spice", rarity: 6600, tier: "legendary" },
    { name: "Gingerbread", rarity: 1150, tier: "legendary" },
    { name: "Maple", rarity: 1250, tier: "legendary" },
    { name: "Maple: Syrup", rarity: 7500, tier: "legendary" },
    { name: "Autumn", rarity: 1400, tier: "legendary" },
    { name: "Autumn: Harvest", rarity: 8400, tier: "mythic" },
    { name: "Cozy", rarity: 1600, tier: "legendary" },
    { name: "Cozy: Fireplace", rarity: 9600, tier: "mythic" },
    { name: "Bookshelf", rarity: 1800, tier: "legendary" },
    { name: "Bookshelf: Library", rarity: 10800, tier: "mythic" },
    { name: "Diaboli", rarity: 1004, tier: "legendary" },
    { name: "Precious", rarity: 1024, tier: "legendary" },
    { name: "Atomic", rarity: 1180, tier: "legendary" },
    { name: "Glock", rarity: 1700, tier: "legendary" },
    { name: "Magnetic", rarity: 2048, tier: "legendary" },
    { name: "Ash", rarity: 2300, tier: "legendary" },
    { name: "Player", rarity: 3000, tier: "legendary" },
    { name: "Fault", rarity: 3000, tier: "legendary" },
    { name: "Pukeko", rarity: 3198, tier: "legendary" },
    { name: "Sand Bucket", rarity: 3500, tier: "legendary" },
    { name: "Cola", rarity: 3999, tier: "legendary" },
    { name: "Cola: Witches Brew", rarity: 399999, tier: "divine" },
    { name: "Flora", rarity: 3700, tier: "legendary" },
    { name: "Sidereum", rarity: 4096, tier: "legendary" },
    { name: "Bleeding", rarity: 4444, tier: "legendary" },
    { name: "Lunar", rarity: 5000, tier: "legendary" },
    { name: "Solar", rarity: 5000, tier: "legendary" },
    { name: "Eclipse", rarity: 10000, tier: "mythic" },
    { name: "Flushed", rarity: 6900, tier: "legendary" },
    { name: "Hazard", rarity: 7000, tier: "legendary" },
    { name: "Quartz", rarity: 8192, tier: "mythic" },
    { name: "Honey", rarity: 8335, tier: "mythic" },
    { name: "Lost Soul", rarity: 9200, tier: "mythic" },
    { name: "Atomic: Riboneucleic", rarity: 9876, tier: "mythic" },
    { name: "★★★", rarity: 10000, tier: "mythic" },
    { name: "Neon", rarity: 10500, tier: "mythic" },
    { name: "Neon: Glow", rarity: 63000, tier: "mythic" },
    { name: "Undead", rarity: 12000, tier: "mythic" },
    { name: "Obsidian", rarity: 13500, tier: "mythic" },
    { name: "Obsidian: Volcanic", rarity: 81000, tier: "mythic" },
    { name: "Titanium", rarity: 18000, tier: "mythic" },
    { name: "Titanium: Alloy", rarity: 99000, tier: "mythic" },
    { name: "Plasma", rarity: 22000, tier: "mythic" },
    { name: "Plasma: Ionized", rarity: 88000, tier: "exotic" },
    { name: "Vortex", rarity: 28000, tier: "mythic" },
    { name: "Vortex: Spiral", rarity: 84000, tier: "exotic" },
    { name: "Prism", rarity: 11500, tier: "mythic" },
    { name: "Corrosive", rarity: 12000, tier: "mythic" },
    { name: "Rage: Heated", rarity: 12800, tier: "mythic" },
    { name: "Rage: Berserker", rarity: 38400, tier: "mythic" },
    { name: "Leak", rarity: 14000, tier: "mythic" },
    { name: "Ink Leak", rarity: 14000, tier: "mythic" },
    { name: "Powered", rarity: 16384, tier: "mythic" },
    { name: "Starfish Rider", rarity: 25000, tier: "mythic" },
    { name: "Copper", rarity: 29000, tier: "mythic" },
    { name: "Watt", rarity: 32768, tier: "mythic" },
    { name: "Watt: Superconductor", rarity: 131072, tier: "exotic" },
    { name: "Aquatic", rarity: 40000, tier: "exotic" },
    { name: "Lightning", rarity: 40000, tier: "exotic" },
    { name: "Starlight", rarity: 50000, tier: "exotic" },
    { name: "Star Rider", rarity: 50000, tier: "exotic" },
    { name: "Flushed: Lobotomy", rarity: 69000, tier: "exotic" },
    { name: "Hazard: Rays", rarity: 70000, tier: "exotic" },
    { name: "Hazard: Fallout", rarity: 210000, tier: "exotic" },
    { name: "Nautilus", rarity: 70000, tier: "exotic" },
    { name: "Permafrost", rarity: 73500, tier: "exotic" },
    { name: "✿ Flow ✿", rarity: 87000, tier: "exotic" },
    { name: "✿ Flow ✿: Stasis", rarity: 261000, tier: "exotic" },
    { name: "Stormal", rarity: 90000, tier: "exotic" },
    { name: "Stormal: Eyewall", rarity: 270000, tier: "exotic" },
    { name: "Pump", rarity: 200000, tier: "exotic" },
    { name: "PUMP : TRICKSTER", rarity: 600000, tier: "divine" },
    { name: "Exotic", rarity: 99999, tier: "exotic" },
    { name: "Diaboli: Void", rarity: 100400, tier: "exotic" },
    { name: "Comet", rarity: 120000, tier: "exotic" },
    { name: "Undead: Devil", rarity: 120000, tier: "exotic" },
    { name: "Divinus: Angel", rarity: 120000, tier: "exotic" },
    { name: "Jade", rarity: 125000, tier: "divine" },
    { name: "Spectre", rarity: 140000, tier: "divine" },
    { name: "Manta", rarity: 300000000, tier: "transcendent" },
    { name: "Jazz", rarity: 160000, tier: "divine" },
    { name: "Aether", rarity: 180000, tier: "divine" },
    { name: "Aether: Quintessence", rarity: 540000, tier: "divine" },
    { name: "Bounded", rarity: 200000, tier: "divine" },
    { name: "Retrospective", rarity: 300000, tier: "divine" },
    { name: "Watermelon", rarity: 320000, tier: "divine" },
    { name: "Celestial", rarity: 350000, tier: "divine" },
    { name: "Terror", rarity: 400000, tier: "divine" },
    { name: "Raven", rarity: 500000, tier: "divine" },
    { name: "Warlock", rarity: 666000, tier: "divine" },
    { name: "Kyawthuite", rarity: 850000, tier: "divine" },
    { name: "Arcane", rarity: 1000000, tier: "celestial" },
    { name: ":troll:", rarity: 1000000, tier: "celestial" },
    { name: "Magnetic: Reverse Polarity", rarity: 1024000, tier: "celestial" },
    { name: "Magnetic: Lodestar", rarity: 3072000, tier: "celestial" },
    { name: "Undefined", rarity: 1111000, tier: "celestial" },
    { name: "Undefined: Defined", rarity: 2222000, tier: "celestial" },
    { name: "Rage: Brawler", rarity: 1280000, tier: "celestial" },
    { name: "Astral", rarity: 1336000, tier: "celestial" },
    { name: "Cosmos", rarity: 1520000, tier: "celestial" },
    { name: "Gravitational", rarity: 2000000, tier: "celestial" },
    { name: "Unbound", rarity: 2000000, tier: "celestial" },
    { name: "Unbound: Freedom", rarity: 6000000, tier: "celestial" },
    { name: "Virtual", rarity: 2500000, tier: "celestial" },
    { name: "Parasite", rarity: 3000000, tier: "celestial" },
    { name: "Lunar C Nightfall", rarity: 3000000, tier: "celestial" },
    { name: "Savior", rarity: 3200000, tier: "celestial" },
    { name: "Shiftlock", rarity: 3325000, tier: "celestial" },
    { name: "Alice", rarity: 3500000, tier: "celestial" },
    { name: "Wonderland", rarity: 4000000, tier: "celestial" },
    { name: "Aquatic: Flame", rarity: 4000000, tier: "celestial" },
    { name: "Poseidon", rarity: 2000000, tier: "celestial" },
    { name: "Zeus", rarity: 4500000, tier: "celestial" },
    { name: "Solar: Solstice", rarity: 5000000, tier: "transcendent" },
    { name: "Solar: Corona", rarity: 15000000, tier: "transcendent" },
    { name: "Galaxy", rarity: 5000000, tier: "transcendent" },
    { name: "Lunar: Full Moon", rarity: 5000000, tier: "transcendent" },
    { name: "Vital", rarity: 6000000, tier: "transcendent" },
    { name: "Anima", rarity: 5730000, tier: "transcendent" },
    { name: "Twilight", rarity: 6000000, tier: "transcendent" },
    { name: "Origin", rarity: 6500000, tier: "transcendent" },
    { name: "Hades", rarity: 6666666, tier: "transcendent" },
    { name: "Hades: Styx", rarity: 20000000, tier: "transcendent" },
    { name: "Hades: Develium", rarity: 777777777, tier: "transcendent" },
    { name: "Celestial: Divine", rarity: 7200000, tier: "transcendent" },
    { name: "Anubis", rarity: 7200000, tier: "transcendent" },
    { name: "Hyper-Volt", rarity: 7500000, tier: "transcendent" },
    { name: "Velocity", rarity: 7630000, tier: "transcendent" },
    { name: "Nautilus: Lost", rarity: 7700000, tier: "transcendent" },
    { name: "Nautilus: Primordial", rarity: 23100000, tier: "transcendent" },
    { name: "Harnessed", rarity: 8500000, tier: "transcendent" },
    { name: "Onion", rarity: 8000000, tier: "transcendent" },
    { name: "Nihility", rarity: 9000000, tier: "transcendent" },
    { name: "Nihility: Void", rarity: 27000000, tier: "transcendent" },
    { name: "Helios", rarity: 9000000, tier: "transcendent" },
    { name: "Stargazer", rarity: 9200000, tier: "transcendent" },
    { name: "Moonflower", rarity: 10000000, tier: "transcendent" },
    { name: "Starscourge", rarity: 10000000, tier: "transcendent" },
    { name: "Sailor", rarity: 12000000, tier: "transcendent" },
    { name: "Sailor: Battleship", rarity: 85000000, tier: "transcendent" },
    { name: "Glitch", rarity: 12210110, tier: "transcendent" },
    { name: "Hurricane", rarity: 13500000, tier: "transcendent" },
    { name: "Sirius", rarity: 14000000, tier: "transcendent" },
    { name: "Santa-Frost", rarity: 15000000, tier: "transcendent" },
    { name: "Arcane: Legacy", rarity: 15000000, tier: "transcendent" },
    { name: "Lullaby", rarity: 17000000, tier: "transcendent" },
    { name: "Lullaby: Sweet Dreams", rarity: 51000000, tier: "transcendent" },
    { name: "Cryptfire", rarity: 21000000, tier: "transcendent" },
    { name: "Dynamic Force", rarity: 65000000, tier: "transcendent" },
    { name: "Chromatic", rarity: 20000000, tier: "transcendent" },
    { name: "Chromatic: Diva", rarity: 105000000, tier: "transcendent" },
    { name: "< Winter Fantasy >", rarity: 24000000, tier: "transcendent" },
    { name: "★ AVIATOR ★", rarity: 24000000, tier: "transcendent" },
    { name: "Aviator: Fleet", rarity: 100000000, tier: "transcendent" },
    { name: "Blizzard", rarity: 27315000, tier: "transcendent" },
    { name: "Arcane: Dark", rarity: 30000000, tier: "transcendent" },
    { name: "Express", rarity: 30000000, tier: "transcendent" },
    { name: "INNOVATOR", rarity: 30000000, tier: "transcendent" },
    { name: "Ethereal", rarity: 35000000, tier: "transcendent" },
    { name: "Soul Hunter", rarity: 40000000, tier: "transcendent" },
    { name: "{ABOMINABLE}", rarity: 40000000, tier: "transcendent" },
    { name: "kr0mat1k", rarity: 40000000, tier: "transcendent" },
    { name: "Fatal Error", rarity: 40413000, tier: "transcendent" },
    { name: "Juxtaposition", rarity: 40440400, tier: "transcendent" },
    { name: "Overseer", rarity: 45000000, tier: "transcendent" },
    { name: "Exotic: Apex", rarity: 49999500, tier: "transcendent" },
    { name: "Matrix", rarity: 50000000, tier: "transcendent" },
    { name: "Runic", rarity: 50000000, tier: "transcendent" },
    { name: "Runic: Eternal", rarity: 150000000, tier: "transcendent" },
    { name: "Sentinel", rarity: 60000000, tier: "transcendent" },
    { name: "M A R T Y R", rarity: 175000000, tier: "transcendent" },
    { name: "Nyctophobia", rarity: 90000000, tier: "transcendent" },
    { name: "Twilight: Iridescent Memory", rarity: 60000000, tier: "transcendent" },
    { name: "Dullahan", rarity: 72000000, tier: "transcendent" },
    { name: "Carriage", rarity: 80000000, tier: "transcendent" },
    { name: "Sailor: Flying Dutchman", rarity: 80000000, tier: "transcendent" },
    { name: "Harnessed: Elements", rarity: 85000000, tier: "transcendent" },
    { name: "Virtual: Worldwide", rarity: 87500000, tier: "transcendent" },
    { name: "Chromatic: Genesis", rarity: 99999999, tier: "transcendent" },
    { name: "Chromatic: Exotic", rarity: 99999999, tier: "transcendent" },
    { name: "Starscourge: Radiant", rarity: 100000000, tier: "transcendent" },
    { name: "Overture", rarity: 150000000, tier: "transcendent" },
    { name: "Atlas : Yuletide", rarity: 170000000, tier: "transcendent" },
    { name: "THE GLOCK OF THE SKY", rarity: 170000000, tier: "transcendent" },
    { name: "Symphony", rarity: 175000000, tier: "transcendent" },
    { name: "Symphony: Eternal", rarity: 525000000, tier: "transcendent" },
    { name: "Nightmare Sky", rarity: 190000000, tier: "transcendent" },
    { name: "Twilight: Withering Grace", rarity: 180000000, tier: "transcendent" },
    { name: "Impeached", rarity: 200000000, tier: "transcendent" },
    { name: "Oppression", rarity: 220000000, tier: "transcendent" },
    { name: "Hyper-Volt: Ever Storm", rarity: 225000000, tier: "transcendent" },
    { name: "《 Shard┃Surfer 》", rarity: 225000000, tier: "transcendent" },
    { name: "Archangel", rarity: 250000000, tier: "transcendent" },
    { name: "Archangel: Overheaven", rarity: 750000000, tier: "transcendent" },
    { name: "Astral: Zodiac", rarity: 267200000, tier: "transcendent" },
    { name: "Astral: Legendarium", rarity: 267200000, tier: "transcendent" },
    { name: "Exotic: Void", rarity: 299999999, tier: "transcendent" },
    { name: "Overture: History", rarity: 300000000, tier: "transcendent" },
    { name: "Overture: Future", rarity: 600000000, tier: "transcendent" },
    { name: "Bloodlust", rarity: 300000000, tier: "transcendent" },
    { name: "Bloodlust: Sanguine", rarity: 600000000, tier: "transcendent" },
    { name: "Maelstrom", rarity: 309999999, tier: "transcendent" },
    { name: "Lotusfall", rarity: 320000000, tier: "transcendent" },
    { name: "Orchestra", rarity: 336970912, tier: "transcendent" },
    { name: "Atlas", rarity: 360000000, tier: "transcendent" },
    { name: "Atlas: A.T.L.A.S", rarity: 700000000, tier: "transcendent" },
    { name: "Flora: Evergreen", rarity: 370073730, tier: "transcendent" },
    { name: "Flora: Photosynthesis", rarity: 111000000, tier: "transcendent" },
    { name: "Chillsear", rarity: 375000000, tier: "transcendent" },
    { name: "Abyssal Hunter", rarity: 400000000, tier: "transcendent" },
    { name: "Abyssal Hunter: Awakened", rarity: 1200000000, tier: "transcendent" },
    { name: "Impeached: I'm Peach", rarity: 400000000, tier: "transcendent" },
    { name: "Aegis - Watergun", rarity: 412500000, tier: "transcendent" },
    { name: "Gargantua", rarity: 430000000, tier: "transcendent" },
    { name: "Sidereum: Starstruck", rarity: 439600000, tier: "transcendent" },
    { name: "Apostolos", rarity: 444000000, tier: "transcendent" },
    { name: "Unknown", rarity: 444444444, tier: "transcendent" },
    { name: "Kyawthuite: Remembrance", rarity: 450000000, tier: "transcendent" },
    { name: "Kyawthuite: Facet", rarity: 25500000, tier: "transcendent" },
    { name: "Ruins", rarity: 500000000, tier: "transcendent" },
    { name: "Matrix: Overdrive", rarity: 503000000, tier: "transcendent" },
    { name: "Dreammetric", rarity: 520000000, tier: "transcendent" },
    { name: "Elude", rarity: 555555555, tier: "transcendent" },
    { name: "Sophyra", rarity: 570000000, tier: "transcendent" },
    { name: "Matrix: Reality", rarity: 601020102, tier: "transcendent" },
    { name: "Prologue", rarity: 666616111, tier: "transcendent" },
    { name: "Harvester", rarity: 666000000, tier: "transcendent" },
    { name: "Sovereign", rarity: 750000000, tier: "transcendent" },
    { name: "Ruins: Withered", rarity: 800000000, tier: "transcendent" },
    { name: "Apostolos: Veil", rarity: 800000000, tier: "transcendent" },
    { name: "Aegis", rarity: 825000000, tier: "transcendent" },
    { name: "Dreamscape", rarity: 850000000, tier: "transcendent" },
    { name: "▣ PIXELATION ▣", rarity: 1073741824, tier: "transcendent" },
    { name: "Luminosity", rarity: 1200000000, tier: "transcendent" },
    { name: "『E Q U I N O X』", rarity: 2500000000, tier: "transcendent" },
    { name: "『E Q U I N O X』: Equilibrium", rarity: 7500000000, tier: "transcendent" },
    { name: "Abomination", rarity: 100000000000, tier: "cosmic" },
    { name: "Memory: The Fallen", rarity: 100, tier: "special" },
    { name: "Oblivion", rarity: 2000, tier: "special" },
    // Mutations
    { name: "Common: Archetype", rarity: 6, tier: "common" },
    { name: "Uncommon: Aberration", rarity: 16, tier: "uncommon" },
    { name: "Good: Virtuous", rarity: 16, tier: "uncommon" },
    { name: "Natural: Overgrowth", rarity: 24, tier: "uncommon" },
    { name: "Natural - Weed", rarity: 8000, tier: "mythic", color: "#2ecc71", font: "bold" },
    { name: "Crystallized: Geode", rarity: 288, tier: "rare" },
    { name: "★: Supernova", rarity: 450, tier: "rare" },
    { name: "Topaz: Charged", rarity: 675, tier: "rare" },
    { name: "Glacier: Winterheart", rarity: 1536, tier: "epic" },
    { name: "Ruby: Incandescent", rarity: 2100, tier: "epic" },
    { name: "Forbidden: Unleashed", rarity: 2424, tier: "epic" },
    { name: "Gilded: Midas", rarity: 3072, tier: "epic" },
    { name: "Ink: Rorschach", rarity: 4200, tier: "epic" },
    { name: "Jackpot: Favor", rarity: 4662, tier: "epic" },
    { name: "Jackpot - Loser", rarity: 7777777, tier: "celestial", color: "#e74c3c", font: "bold" },
    { name: "Wind: Tempest", rarity: 5400, tier: "epic" },
    { name: "Precious: Priceless", rarity: 7680, tier: "legendary" },
    { name: "Glock: Ricochet", rarity: 12750, tier: "legendary" },
    { name: "Ash: Phoenix", rarity: 16100, tier: "legendary" },
    { name: "Ash - Charcoal", rarity: 10456, tier: "legendary", color: "#34495e", font: "italic" },
    { name: "Pukeko: Guardian", rarity: 22385, tier: "legendary" },
    { name: "Sand Bucket: Castle", rarity: 24500, tier: "legendary" },
    { name: "Cola: Effervescence", rarity: 27995, tier: "legendary" },
    { name: "Quartz: Resonant", rarity: 61440, tier: "mythic" },
    { name: "Honey: Ambrosia", rarity: 62515, tier: "mythic" },
    { name: "Lost Soul: Vengeful", rarity: 69000, tier: "mythic" },
    { name: "Corrosive: Meltdown", rarity: 90000, tier: "mythic" },
    { name: "Starfish Rider: Celestial", rarity: 187500, tier: "exotic" },
    { name: "Jade: Dragon", rarity: 625000, tier: "divine" },
    { name: "Spectre: Poltergeist", rarity: 700000, tier: "divine" },
    { name: "Jazz: Blues", rarity: 800000, tier: "divine" },
    { name: "Bounded: Paradox", rarity: 1000000, tier: "divine" },
    { name: "Arcane : Reversal", rarity: 500000, tier: "divine", color: "#9b59b6", font: "bold italic" },
    { name: "Watermelon: Rush", rarity: 1600000, tier: "divine" },
    { name: "Gravitational: Wormhole", rarity: 8000000, tier: "celestial" },
    { name: "Gravitational - Event Horizon", rarity: 200000000, tier: "transcendent", color: "#000000", font: "bold", glow: "#ff00ff" },
    { name: "Poseidon: Cybernetic", rarity: 8400000, tier: "celestial" },
    { name: "Zeus: Olympian", rarity: 18900000, tier: "celestial" },
    { name: "Anubis: Scales", rarity: 43200000, tier: "transcendent" },
    { name: "Glitch: Segfault", rarity: 73265670, tier: "transcendent" },
    { name: "Archangel: Seraphim", rarity: 1500000000, tier: "transcendent" },
    { name: "Sovereign: Divine", rarity: 4500000000, tier: "transcendent" },
    // Additional Mutations
    { name: "Emerald: Verdant", rarity: 3000, tier: "epic" },
    { name: "Sapphire: Insight", rarity: 4800, tier: "epic" },
    { name: "Aquamarine: Abyss", rarity: 5400, tier: "epic" },
    { name: "★★: Binary", rarity: 6000, tier: "legendary" },
    { name: "Player: HUD", rarity: 18000, tier: "legendary" },
    { name: "Player: Invader", rarity: 21000, tier: "legendary" },
    { name: "Fault: Tectonic", rarity: 18000, tier: "legendary" },
    { name: "Sidereum: Constellation", rarity: 24575, tier: "legendary" },
    { name: "Bleeding: Ichor", rarity: 26665, tier: "legendary" },
    { name: "★★★: Trinary", rarity: 60000, tier: "mythic" },
    { name: "Powered: Overclocked", rarity: 98305, tier: "mythic" },
    { name: "Leak: Breach", rarity: 84000, tier: "mythic" },
    { name: "Copper: Patina", rarity: 174000, tier: "exotic" },
    { name: "Lightning: Kugelblitz", rarity: 240000, tier: "exotic" },
    { name: "Starlight: Alpenglow", rarity: 300000, tier: "exotic" },
    { name: "Permafrost: Rime", rarity: 441000, tier: "exotic" },
    { name: "Comet: Impactor", rarity: 720000, tier: "exotic" },
    { name: "Comet - Halley", rarity: 120000000, tier: "transcendent", color: "#3498db", font: "bold italic" },
    { name: "Manta: Aetherwing", rarity: 825000000, tier: "transcendent" },
    { name: "Terror: Phobia", rarity: 2200000, tier: "divine" },
    { name: "Warlock: Patron", rarity: 3663000, tier: "divine" },
    { name: "Cosmos: Singularity", rarity: 8000000, tier: "celestial" },
    { name: "Parasite: Symbiote", rarity: 15750000, tier: "celestial" },
    { name: "Alice: Glass", rarity: 18375000, tier: "celestial" },
    { name: "Galaxy: Quasar", rarity: 27500000, tier: "transcendent" },
    { name: "『E Q U I N O X』: Zenith", rarity: 3750000000, tier: "transcendent" },
    { name: "▣ PIXELATION ▣: Voxel", rarity: 6442450945, tier: "transcendent" },
    // Additional New Mutations
    { name: "Raven: Nevermore", rarity: 2750000, tier: "divine" },
    { name: ":troll:: Epic", rarity: 5500000, tier: "celestial" },
    { name: "Savior: Messiah", rarity: 16800000, tier: "celestial" },
    { name: "Shiftlock: First Person", rarity: 18137500, tier: "celestial" },
    { name: "Wonderland: Looking Glass", rarity: 20000000, tier: "celestial" },
    { name: "Vital: Lifeforce", rarity: 33000000, tier: "transcendent" },
    { name: "Anima: Spiritus", rarity: 28650000, tier: "transcendent" },
    { name: "Origin: Genesis", rarity: 35750000, tier: "transcendent" },
    { name: "Velocity: Hypersonic", rarity: 42315000, tier: "transcendent" },
    { name: "Onion: Layers", rarity: 44000000, tier: "transcendent" },
    { name: "Helios: Radiance", rarity: 49500000, tier: "transcendent" },
    { name: "Stargazer: Constellation", rarity: 50600000, tier: "transcendent" },
    { name: "Moonflower: Bloom", rarity: 55000000, tier: "transcendent" },
    { name: "Hurricane: Cyclone", rarity: 67500000, tier: "transcendent" },
    { name: "Sirius: Binary Star", rarity: 70000000, tier: "transcendent" },
    { name: "Sirius - Nebula", rarity: 140000000, tier: "transcendent", color: "#e91e63", font: "bold" },
    { name: "Santa-Frost: Blitzen", rarity: 82500000, tier: "transcendent" },
    { name: "Cryptfire: Inferno", rarity: 115500000, tier: "transcendent" },
    { name: "Dynamic Force: Kinetic", rarity: 357500000, tier: "transcendent" },
    { name: "< Winter Fantasy >: Snowfall", rarity: 120000000, tier: "transcendent" },
    { name: "Blizzard: Whiteout", rarity: 150093750, tier: "transcendent" },
    { name: "Express: Bullet Train", rarity: 165000000, tier: "transcendent" },
    { name: "INNOVATOR: Inventor", rarity: 165000000, tier: "transcendent" },
    { name: "Ethereal: Phantom", rarity: 192500000, tier: "transcendent" },
    { name: "Soul Hunter: Reaper", rarity: 220000000, tier: "transcendent" },
    { name: "{ABOMINABLE}: Yeti", rarity: 220000000, tier: "transcendent" },
    { name: "kr0mat1k: RGB", rarity: 220000000, tier: "transcendent" },
    { name: "Fatal Error: Exception", rarity: 222275665, tier: "transcendent" },
    { name: "Juxtaposition: Contrast", rarity: 222402200, tier: "transcendent" },
    { name: "Overseer: Watcher", rarity: 247500000, tier: "transcendent" },
    { name: "Sentinel: Guardian", rarity: 330000000, tier: "transcendent" },
    { name: "M A R T Y R: Sacrifice", rarity: 962500000, tier: "transcendent" },
    { name: "Nyctophobia: Darkness", rarity: 495000000, tier: "transcendent" },
    { name: "Dullahan: Headless", rarity: 396000000, tier: "transcendent" },
    { name: "Carriage: Golden", rarity: 440000000, tier: "transcendent" },
    { name: "THE GLOCK OF THE SKY: Divine Arms", rarity: 935000000, tier: "transcendent" },
    { name: "Nightmare Sky: Abyss", rarity: 1045000000, tier: "transcendent" },
    { name: "Oppression: Tyranny", rarity: 1210000000, tier: "transcendent" },
    { name: "《 Shard┃Surfer 》: Wave Rider", rarity: 1237500000, tier: "transcendent" },
    { name: "Maelstrom: Vortex", rarity: 1704999995, tier: "transcendent" },
    { name: "Lotusfall: Petal Storm", rarity: 1760000000, tier: "transcendent" },
    { name: "Orchestra: Crescendo", rarity: 1853853650, tier: "transcendent" },
    { name: "Chillsear: Frostburn", rarity: 2062500000, tier: "transcendent" },
    { name: "Gargantua: Titan", rarity: 2365000000, tier: "transcendent" },
    { name: "Dreammetric: Lucid", rarity: 2860000000, tier: "transcendent" },
    { name: "Elude: Phantom", rarity: 3055555555, tier: "transcendent" },
    { name: "Sophyra: Wisdom", rarity: 3135000000, tier: "transcendent" },
    { name: "Prologue: Beginning", rarity: 3666080555, tier: "transcendent" },
    { name: "Harvester: Scythe", rarity: 3663000000, tier: "transcendent" },
    { name: "Dreamscape: Reverie", rarity: 4675000000, tier: "transcendent" },
    { name: "Dreamscape - Nightmare", rarity: 1850000000, tier: "transcendent", color: "#8b00ff", font: "bold italic", glow: "#ff0000" },
    { name: "Luminosity: Brilliant", rarity: 6600000000, tier: "transcendent" },
    // Limbo Exclusives (only obtainable in The Limbo)
    { name: "Unknown", rarity: 444444444, tier: "transcendent" }, // Already exists but keeping for Limbo
    // Ultra Rare Mastermind Aura
    { name: "Mastermind", rarity: 50000000000, tier: "cosmic" },
    // Brand New Unique Auras
    { name: "Marionette", rarity: 22000000, tier: "transcendent" }, // Puppet/strings theme
    { name: "Marionette: Puppeteer", rarity: 121000000, tier: "transcendent" },
    { name: "Kaleidoscope", rarity: 8500000, tier: "celestial" }, // Shifting patterns theme
    { name: "Kaleidoscope: Fractal", rarity: 46750000, tier: "transcendent" },
    { name: "Mirage", rarity: 15000000, tier: "celestial" }, // Desert illusion theme
    { name: "Mirage: Oasis", rarity: 82500000, tier: "transcendent" },
    { name: "Clockwork", rarity: 12000000, tier: "celestial" }, // Mechanical/steampunk theme
    { name: "Clockwork: Automaton", rarity: 66000000, tier: "transcendent" },
    { name: "Carnival", rarity: 19000000, tier: "celestial" }, // Circus/festival theme
    { name: "Carnival: Ringmaster", rarity: 104500000, tier: "transcendent" },
    // Ultra Rare Hunter Constellation
    { name: "Orion", rarity: 10000000000, tier: "cosmic" },
    // Crimson Biome Auras (Terraria-inspired)
    { name: "Crimson", rarity: 8000, tier: "mythic" },
    { name: "Crimson: Flesh", rarity: 48000, tier: "mythic" },
    { name: "Crimson: Ichor", rarity: 240000, tier: "exotic" },
    { name: "Vertebrae", rarity: 15000, tier: "mythic" },
    { name: "Vertebrae: Spine", rarity: 82500, tier: "mythic" },
    { name: "Hemogoblin", rarity: 35000, tier: "mythic" },
    { name: "Hemogoblin: Crimson Heart", rarity: 192500, tier: "exotic" },
    { name: "Brain", rarity: 412500000, tier: "transcendent" },
    { name: "Crimtane", rarity: 25000, tier: "mythic" },
    { name: "Crimtane: Ore", rarity: 137500, tier: "exotic" },
    { name: "Vicious", rarity: 50000, tier: "exotic" },
    { name: "Vicious: Tendril", rarity: 275000, tier: "divine" },
    // Additional New Auras
    { name: "Meteor", rarity: 200005, tier: "divine" },
    { name: "Radiation", rarity: 82000, tier: "exotic" },
    { name: "Fault: Fatal", rarity: 303330, tier: "divine" },
    { name: "Impeached: Emperor", rarity: 400000000, tier: "transcendent" },
    { name: "Manipulative", rarity: 23235000, tier: "transcendent" },
    { name: "Dataglow", rarity: 96342387, tier: "transcendent" },
    { name: "Atomic: Nucleus", rarity: 118000000, tier: "transcendent" },
    { name: "Lament", rarity: 202020202, tier: "transcendent" },
    { name: "Cosmos: Necrolia", rarity: 1520000000, tier: "transcendent" },
    { name: "Leviathan", rarity: 1550530000, tier: "transcendent" },
    { name: "Showdown", rarity: 1650000000, tier: "transcendent" },
    { name: "《Celestial: Memoria Aeternum》", rarity: 5000000000, tier: "transcendent" },
    { name: "Eden", rarity: 999999999999, tier: "legendary" }, // Unobtainable without Voidheart potion (becomes 1/1000 with Voidheart)
    // Halloween Biome Auras
    // Pumpkin Moon Exclusive
    { name: "Pumpkin", rarity: 5000, tier: "legendary" },
    { name: "Pumpkin: Spice", rarity: 30000, tier: "mythic" },
    { name: "Pumpkin: Lantern", rarity: 150000, tier: "exotic" },
    { name: "Gingerbread: Haunted", rarity: 250000, tier: "divine" },
    { name: "Headless :Horseman", rarity: 23000000, tier: "transcendent" }, // ONLY Pumpkin Moon
    { name: "PHANTASMA", rarity: 462000000, tier: "transcendent" }, // ONLY Pumpkin Moon
    { name: "< A R A C H N O P H O B I A >", rarity: 940000000, tier: "transcendent" }, // ONLY Pumpkin Moon
    // Graveyard Exclusive
    { name: "Headless", rarity: 3200000, tier: "celestial" },
    { name: "APOCALYPSE", rarity: 624000000, tier: "transcendent" }, // ONLY Graveyard
    { name: "〔BANSHEE〕", rarity: 730000000, tier: "transcendent" }, // ONLY Graveyard
    { name: "RAVAGE", rarity: 930000000, tier: "transcendent" }, // ONLY Graveyard
    // Blood Rain Exclusive
    { name: "Vampiric", rarity: 8500000, tier: "transcendent" },
    { name: "Vampiric: Bloodmoon", rarity: 51000000, tier: "transcendent" },
    { name: "Accursed", rarity: 82000000, tier: "transcendent" }, // ONLY Blood Rain
    { name: "MALEDICTION", rarity: 730000000, tier: "transcendent" }, // ONLY Blood Rain
    { name: "LAMENTHYR", rarity: 1000000000, tier: "transcendent" }, // ONLY Blood Rain
    { name: "Erebus", rarity: 1200000000, tier: "transcendent" }, // ONLY Blood Rain
    // Halloween Shop Exclusive (Bounty Hunter Jack)
    { name: "THANEBORNE", rarity: 999999999999, tier: "cosmic" }, // 25,000 Halloween Bounty Medals
    // Halloween Mutations for existing auras (native to Halloween biomes)
    { name: "Autumn: Spooky", rarity: 16800, tier: "mythic" },
    { name: "Rage: Bloodrage", rarity: 256000, tier: "exotic" },
    { name: "Undead: Lich", rarity: 240000, tier: "exotic" },
    { name: "Terror: Nightmare", rarity: 2800000, tier: "divine" },
    { name: "Raven: Omen", rarity: 3500000, tier: "divine" },
    { name: "Lost Soul: Tormented", rarity: 64400, tier: "mythic" },
    { name: "Spectre: Wraith", rarity: 980000, tier: "divine" },
    { name: "Nightmare Sky: Eclipse", rarity: 1330000000, tier: "transcendent" },
    { name: "Diaboli: Hellspawn", rarity: 804000, tier: "divine" },
    { name: "Bloodlust: Carnage", rarity: 2100000000, tier: "transcendent" },
    { name: "Crimson: Corruption", rarity: 560000, tier: "divine" },
    { name: "Ruby: Bloodstone", rarity: 2800, tier: "epic" },
    { name: "Bleeding: Hemophilia", rarity: 35552, tier: "legendary" },
    { name: "Dullahan: Reaper", rarity: 528000000, tier: "transcendent" },
    // New mutations for previously unmutated auras
    { name: "Eclipse: Total", rarity: 60000, tier: "mythic" },
    { name: "Ink Leak: Flood", rarity: 84000, tier: "mythic" },
    { name: "Prism: Spectrum", rarity: 69000, tier: "mythic" },
    { name: "Radiation: Ultraviolet", rarity: 492000, tier: "exotic" },
    { name: "Star Rider: Nebula", rarity: 300000, tier: "exotic" },
    { name: "Meteor: Impact", rarity: 1200000, tier: "divine" },
    { name: "Retrospective: Nostalgia", rarity: 1800000, tier: "divine" },
    { name: "Lunar C Nightfall: Eclipse", rarity: 18000000, tier: "transcendent" },
    { name: "Manipulative: Puppetmaster", rarity: 139410000, tier: "transcendent" },
    { name: "Dataglow: Binary", rarity: 578034322, tier: "transcendent" },
    { name: "Lament: Requiem", rarity: 1111111110, tier: "transcendent" },
    { name: "Showdown: High Noon", rarity: 9075000000, tier: "transcendent" },
    { name: "Leviathan: Depths", rarity: 8527650000, tier: "transcendent" },
    { name: "Aegis: Fortress", rarity: 4537500000, tier: "transcendent" }
];

// Export to window for global access
window.AURAS = AURAS;
console.log(`✅ Loaded ${AURAS.length} auras into window.AURAS`);
