// ============================================================================
// STAGE 1: ALL TRACKING VARIABLES FOR 221 MISSING ACHIEVEMENT TYPES
// ============================================================================
// Add these to gameState.achievements.stats (after rollsSinceCommon: 0)

// Deletion/Management Tracking (11 types)
exoticDeletes: 0,
commonsDeleted: 0,
deletesAt66: 0,
legendaryDeletes: 0,
mythicDeletes: 0,
totalDeletes: 0,
deletionHistory: [],
noDeleteStreak: 0,
accidentalExoticDeletes: 0,
craftWithoutUse: 0,
inventoryFull: false,

// Advanced Biome Tracking (17 types)
biomeVisitCounts: {},
biomeSpeedrunRecord: 0,
weeklyBiomesTracked: [],
biomeCombosCompleted: 0,
allBiomesSeen: [],
allBiomes1000Done: false,
biomeChampion: false,
biomeCompletionist: false,
bloodRainVisits: 0,
celestialBiomesVisited: 0,
dangerBiomesVisited: 0,
extremeBiomesVisited: 0,
graveyardVisits: 0,
pumpkinMoonVisits: 0,
starfallVisits: 0,
weatherBiomesVisited: 0,
solarLunarHourDone: false,

// Luck & Rarity Tracking (22 types)
highRarityNoBuffsList: [],
billionBaseLuckRolls: 0,
blessedByRNG: 0,
consistentLuckStreak: 0,
earlyGameLucky: false,
earlyLuckRareCount: 0,
fortuneFavored: 0,
fortuneSmile: 0,
insaneLuck100m: false,
lowLuckBillionDone: false,
luckChainCount: 0,
luckMastery: 0,
luckSpikeCount: 0,
luckyAfterUnluckyDone: false,
luckyStreakBest: 0,
millionLuckRolls: 0,
mythicBaseLuckDone: false,
noBuffMythicDone: false,
reverseLuckDone: false,
transcendentBaseLuckDone: false,
againstOddsDone: false,
blessedRNGCount: 0,

// Rolling Pattern Tracking (22 types)
autoMarathonDone: false,
billionRollsDone: false,
daily100kRollsDone: false,
dailyBillionAurasDone: false,
dailyRollAddictDone: false,
dawnPatrolRolls: 0,
exact420Done: false,
exact69Done: false,
exact1337PotionDone: false,
exact777CoinsDone: false,
exactStreaksCompleted: {},
firstRollDivineDone: false,
goldenHourRolls: 0,
hourlyRollTracker: {},
insaneSpeedRolls: 0,
lightSpeedRolls: 0,
marathonRollingDone: false,
midnightRollsCount: 0,
nakedRollsCount: 0,
overnightAutoRollDone: false,
rapidRollsCount: 0,
session666Done: false,

// Speed & Timing (9 types)
fastExoticCount: 0,
perfectTimingDone: false,
slowRollsCount: 0,
speedRollingCount: 0,
speedRollingProDone: false,
weekendRollsTotal: 0,
weekly50kDone: false,
yearStreakDays: 0,
voluntaryBreakDone: false,

// Streaks & Combos (18 types)
breakthroughChainMax: 0,
comebackKingDone: false,
commonStreakMax: 0,
consecutiveCombos: 0,
divineStreakCount: 0,
divineStreak100Done: false,
escalationCombos: 0,
noCommonComboCount: 0,
noCommons100kDone: false,
noCommons10kDone: false,
noLegendary10kDone: false,
noLegendaryStreakMax: 0,
sameCommon100Done: false,
sessionCombosCompleted: [],
themeCombosCount: 0,
tierClimbStreak: 0,
transcendentStreakCount: 0,
transcendentStreak50Done: false,

// Mutations Extended (7 types)
mutationChainInsaneMax: 0,
mutationCollectionDone: false,
mutationHuntingCount: 0,
mutationObtainedFirst: false,
mutationPairsCount: 0,
mutationSupremeDone: false,
uniqueMutationsList: [],

// Halloween Extended (13 types)
dailyHalloweenBiomesList: [],
glitchAurasCount: 0,
glitchBiomesCount: 0,
halloweenAurasList: [],
halloweenBiomeTripleDone: false,
halloweenBiomesSeenList: [],
halloweenCompleteDone: false,
halloweenGodDone: false,
halloweenMedalBalancePeak: 0,
halloweenMedalsEarnedTotal: 0,
halloweenRunesUsedCount: 0,
halloweenSupremeDone: false,
pumpkinAuraDone: false,

// Merchants (7 types)
jackPurchasesCount: 0,
jesterPurchasesCount: 0,
mariPurchasesCount: 0,
merchantBillionDone: false,
merchantSpendingTotal: 0,
metBountyJackDone: false,
moneySpentMerchantsTotal: 0,

// Currency (11 types)
darkPointsEarnedTotal: 0,
moneyBalancePeak: 0,
moneyGainFastestAmount: 0,
moneyLossFastestAmount: 0,
voidCoin100kDone: false,
voidCoinBalancePeak: 0,
voidCoinsEarnedTotal: 0,
voidCoinsLifetimeTotal: 0,
voidCoinsSpentTotal: 0,
zeroMoneyRollsCount: 0,
exact777CoinsBalanceDone: false,

// Potions Extended (12 types)
allPotions10kDone: false,
clarityUsedCount: 0,
hindsightRerollsCount: 0,
jackpotTriggeredCount: 0,
oblivionUsedCount: 0,
oneRollPotionsCount: 0,
phoenixRevivalsCount: 0,
potionHoardMaxAmount: 0,
potionOverdoseCount: 0,
potionStackMaxCount: 0,
potionsConservedCount: 0,
quantumChainMaxLength: 0,

// Runes Extended (6 types)
allRunes5kDone: false,
runeEclipseUsedCount: 0,
runeEverythingUsedCount: 0,
runeStackMaxCount: 0,
singleRuneHoardMax: 0,
totalRunesUsedLifetime: 0,

// Gears Extended (9 types)
crimsonHeartBonusCount: 0,
gearCollectionCompleteDone: false,
gemstoneTriggersCount: 0,
orionBeltEquippedMinutes: 0,
tier10BothSlotsDone: false,
tier10CompleteDone: false,
uniqueGearsCraftedCount: 0,
divineOneGearDone: false,
cosmicObtainedDone: false,

// Collections (13 types)
cosmicCollectionDone: false,
cosmicAurasCount: 0,
elementCollectionsList: {},
elementMasterDone: false,
errorTrioDone: false,
godlyTrioDone: false,
oneAuraMillionDone: false,
oneEachAuraDone: false,
onlyOneTypeDone: false,
over9000AuraDone: false,
powerTrinityDone: false,
starCollectionSimultaneousDone: false,
transcendentCollectionCount: 0,

// Crafting Extended (5 types)
dailyCraftingInsaneDone: false,
dailyCraftCountToday: 0,
darklightCraftsCount: 0,
millionCraftsDone: false,
uniquePotionsCraftedCount: 0,

// Daily/Session Extended (9 types)
dailyBiomeChangesCount: 0,
dailyBreakthroughsCount: 0,
dailyChestOpeningCount: 0,
dailySessionsCount: 0,
earlyLoginDone: false,
perfectDayRollsDone: false,
perfectSessionDone: false,
sessionBreakthroughsCount: 0,
voluntaryBreakTaken: false,

// Special/Meme/Godlike (14 types)
bigBrainStacksCount: 0,
earlyMythicTrioDone: false,
elementalSessionDone: false,
f2pGrindDone: false,
godlikeMasterDone: false,
insaneMasterDone: false,
memeMasterDone: false,
painAfterGloryDone: false,
rareMutationRarity: 0,
rareSessionComboCount: 0,
raritySurgeCount: 0,
rollingSupremeDone: false,
specificMasterDone: false,
syrupUsedCount: 0,

// Ultimate (7 types)
millionBreakthroughsDone: false,
trillionRarityDone: false,
ultimateBreakthroughsDone: false,
ultimateCollectionDone: false,
ultimateMasterDone: false,
ultimateRarityDone: false,
ultimateRollsDone: false,

// Misc Tracking
manualOnlyRollsCount: 0,
uniquePotionsOwnedList: [],
unluckyStreakMax: 0,
rareSessionCombos: 0,
session666Completed: false,
comboMasterCount: 0,
luckSupremeDone: false,
